### ISSUE TITLE
CI npm error

### ISSUE THREAD

**Issue by thomasJang** [ax5ui/ax5ui-kernel#101]
```
npm WARN using --force I sure hope you know what you are doing.
VERSION :  1.4.11
START VERSION UP PROCESS
npm WARN engine figures@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine cli-cursor@2.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine string-width@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine restore-cursor@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine onetime@2.0.1: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})
npm WARN engine mimic-fn@1.1.0: wanted: {"node":">=4"} (current: {"node":"0.12.5","npm":"2.11.2"})

> opencollective-postinstall@1.0.15 postinstall /data/deploy/.jenkins/jobs/AX5-KERNEL/workspace/node_modules/opencollective-postinstall
> ./bin/setup.js

/data/deploy/.jenkins/jobs/AX5-KERNEL/workspace/node_modules/opencollective-postinstall/bin/setup.js:38
  debug(`Parent dir (${parentDir}) is not "node_modules", exiting`);
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Linux 2.6.32-573.22.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! opencollective-postinstall@1.0.15 postinstall: `./bin/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the opencollective-postinstall@1.0.15 postinstall script './bin/setup.js'.
npm ERR! This is most likely a problem with the opencollective-postinstall package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/setup.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls opencollective-postinstall
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /data/deploy/.jenkins/jobs/AX5-KERNEL/workspace/npm-debug.log
```

**Comment by brant-hwang** [comment]
resolved by updating node version. 

now, CI has followed node & npm version.

[deploy@chequer bin]$ node -v
v6.10.2
[deploy@chequer bin]$ npm -v
3.10.10

**Comment by thomasJang** [comment]
npm: command not found

logs
```
./build.sh: line 22: npm: command not found
VERSION : 
START VERSION UP PROCESS
./build.sh: line 31: npm: command not found
```

npm: command not found
